### ISSUE TITLE
`model.set_weights()` with ray backend throws an error when EARLY STOPPING

### ISSUE THREAD

**Issue by zhisbug** [ludwig-ai/ludwig#1137]
**Describe the bug**
When training petfinder dataset (see [here ](https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/train.py)for example code) using Ray backend, after a few epochs when EARLY STOPPING is triggered, an error is thrown with the following trace:
```python
Traceback (most recent call last):
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig-petfinder/petfinder-adoption-prediction/train.py", line 34, in <module>
    ) = model.train(dataset=dataset_to_use)
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig/ludwig/api.py", line 480, in train
    save_path=model_dir,
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig/ludwig/backend/ray.py", line 117, in train
    model.set_weights(weights)
  File "/home/hao.zhang/project/pycharm/ludwig-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1857, in set_weights
    (self.name, len(weights), expected_num_weights, str(weights)[:50]))
ValueError: You called `set_weights(weights)` on layer "ecd" with a weight list of length 30, but the layer was expecting 16 weights. Provided weights: [array([[ 0.3757825 , -0.03104234,  0.8619888 , .....

```

Seems that the `model.set_weights` function under Ray backend has issues because this won't happen in local mode (w/o using Ray backend.)

**Environment (please complete the following information):**
 - OS: Ubuntu 18
- Python version: 3.6
- Ludwig version: master

**Additional context**

**Comment by tgaddair** [comment]
Hey @zhisbug, I ran across a similar issue after fixing the IterableBatcher. The PR #1138 fixed it for me. Can you try running again with this branch?

**Comment by zhisbug** [comment]
@tgaddair re-tested and it works now. thanks!! We can close this issue!
