### ISSUE TITLE
Latest master expects a test.hdf5 no matter what

### ISSUE THREAD

**Issue by carlogrisetti** [ludwig-ai/ludwig#1185]
(hahahahaha I opened this issue on another project, and was wondering why it took so long for you guys to respond, since you're really quick usually hahah)

Training from latest master, with a force_split = False and the valued split column in the dataset.csv file.
If you only specify split 0 and 1 (to have only the training and validation dataset), this works correctly when no .hdf5 is present and Ludwig has to generate it the first time. Ludwig correctly generates a training.hdf5 and validation.hdf5, but no test.hdf5 (since no test split is present)

Once you want to do another training without changing the dataset and\or data-related parameters in the config.yaml, Ludwig should use the already present hdf5 files. It tries to, but it is still looking for the test.hdf5 that was never generated in the first place.

Found cached dataset and meta.json with the same filename of the dataset, using them instead
Using full hdf5 and json
Loading data from: dataset.training.hdf5
Loading data from: dataset.validation.hdf5
Loading data from: dataset.test.hdf5 `<--- this should not happen, since there is no test dataset`
Traceback (most recent call last):
File "c:\program files\python38\lib\runpy.py", line 192, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\program files\python38\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Program Files\Python38\Scripts\ludwig.exe_main.py", line 7, in
File "c:\program files\python38\lib\site-packages\ludwig\cli.py", line 146, in main
CLI()
File "c:\program files\python38\lib\site-packages\ludwig\cli.py", line 72, in init
getattr(self, args.command)()
File "c:\program files\python38\lib\site-packages\ludwig\cli.py", line 77, in train
train.cli(sys.argv[2:])
File "c:\program files\python38\lib\site-packages\ludwig\train.py", line 412, in cli
train_cli(**vars(args))
File "c:\program files\python38\lib\site-packages\ludwig\train.py", line 180, in train_cli
model.train(
File "c:\program files\python38\lib\site-packages\ludwig\api.py", line 394, in train
preprocessed_data = self.preprocess(
File "c:\program files\python38\lib\site-packages\ludwig\api.py", line 1263, in preprocess
preprocessed_data = preprocess_for_training(
File "c:\program files\python38\lib\site-packages\ludwig\data\preprocessing.py", line 1400, in preprocess_for_training
processed = data_format_processor.prepare_processed_data(
File "c:\program files\python38\lib\site-packages\ludwig\data\preprocessing.py", line 1015, in prepare_processed_data
test_set = load_hdf5(test_set,
File "c:\program files\python38\lib\site-packages\ludwig\data\preprocessing.py", line 1307, in load_hdf5
dataset = data_utils.load_hdf5(hdf5_file_path)
File "c:\program files\python38\lib\site-packages\ludwig\utils\data_utils.py", line 276, in load_hdf5
with download_h5(data_fp) as hdf5_data:
File "c:\program files\python38\lib\contextlib.py", line 113, in enter
return next(self.gen)
File "c:\program files\python38\lib\site-packages\ludwig\utils\fs_utils.py", line 105, in download_h5
local_path = fsspec.open_local(url)
File "c:\program files\python38\lib\site-packages\fsspec\core.py", line 463, in open_local
with of as files:
File "c:\program files\python38\lib\site-packages\fsspec\core.py", line 184, in enter
return [s.enter() for s in self]
File "c:\program files\python38\lib\site-packages\fsspec\core.py", line 184, in
return [s.enter() for s in self]
File "c:\program files\python38\lib\site-packages\fsspec\core.py", line 102, in enter
f = self.fs.open(self.path, mode=mode)
File "c:\program files\python38\lib\site-packages\fsspec\spec.py", line 942, in open
f = self._open(
File "c:\program files\python38\lib\site-packages\fsspec\implementations\local.py", line 120, in _open
return LocalFileOpener(path, mode, fs=self, **kwargs)
File "c:\program files\python38\lib\site-packages\fsspec\implementations\local.py", line 202, in init
self._open()
File "c:\program files\python38\lib\site-packages\fsspec\implementations\local.py", line 207, in _open
self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/some_path/dataset.test.hdf5'

Of course a workaround to this is to just provide a single row (even duplicate) in the dataset.csv file with a split of 2, so that the test.hdf5 is generated and then can be loaded again in the future.

One thing that might not be obvious: I am not passing separate splits from the commandline, but using the --dataset dataset.csv parameter which contains splits 0 and 1 only

**Comment by tgaddair** [comment]
Thanks for reporting @carlogrisetti. This will be fixed by #1176, but there are currently some test failures / design tradeoffs being explored there.

cc @w4nderlust

**Comment by tgaddair** [comment]
Hey @carlogrisetti, can you try #1189 and let me know if it fixes the issue for you?
