### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by m-kazuya** [ludwig-ai/ludwig#1259]
Hi,
I'm trying create a face recognition model using the following dataset: http://vis-www.cs.umass.edu/lfw/, however,  I cannot start training because of the following error: 
...
>Using training raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading training file...
done
Loading validation file..
done
Loading test file..
done
Concatenating files..
done
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/ludwig/features/image_feature.py", line 119, in _read_image_and_resize
    img = imread(img_entry)
  File "/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python3.6/dist-packages/skimage/io/manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode
"""

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 136, in main
    CLI()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 71, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 75, in train
    train.cli(sys.argv[2:])
  File "/usr/local/lib/python3.6/dist-packages/ludwig/train.py", line 419, in cli
    train_cli(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/ludwig/train.py", line 198, in train_cli
    debug=debug,
  File "/usr/local/lib/python3.6/dist-packages/ludwig/api.py", line 412, in train
    **kwargs,
  File "/usr/local/lib/python3.6/dist-packages/ludwig/api.py", line 1279, in preprocess
    random_seed=random_seed
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 1498, in preprocess_for_training
    random_seed=random_seed
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 243, in preprocess_for_training
    random_seed=random_seed
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 1628, in _preprocess_file_for_training
    random_seed=random_seed
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 1150, in build_dataset
    skip_save_processed_input
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 1293, in build_data
    skip_save_processed_input
  File "/usr/local/lib/python3.6/dist-packages/ludwig/features/image_feature.py", line 349, in add_feature_data
    read_image_and_resize, all_img_entries
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Could not find a format to read the specified file in single-image mode

On the other hand, I've created a image classification model using MNIST dataset. I have no idea why I have the above error when using the LFW dataset.

The config file is : 
```
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
output_features:
    -
        name: name
        type: category
```

and training csv is : 
```
image_path, name
hogehoge, hogehoge
...
```

__Expected behavior__
I expect to clear the above error.

__Environment__
-OS: Ubuntu18(docker, host OS: windows10)
-Python: 3.6
-Ludwig: 0.4

**Comment by jimthompson5802** [comment]
@m-kazuya   

My first impression based on the information provided is that the `image_path` value in the csv data set may be incorrect.  The value should be the fully qualified path location for an image.  the sample value shown does not appear to be that.  I would have expected `image_path` value would be something like `<parent_directory_paths>/hogehoge.jpg`
```
image_path, name
hogehoge, hogehoge
...
```

Are you showing an actual row in your training data set or an "illustrative" example?

If the above advice does not help you with a solution,  I'll need additional details.

* What version of the data are you using?
![image](https://user-images.githubusercontent.com/1425269/129823988-fdbc37c8-c456-4147-a9c7-83c0c6ccaace.png)
* Please provide the full command used to invoke Ludwig.
* Please provide the full run time log where the error occurs.
* What does the directory structure of the training data look like?  
* Please post the first 10 rows of the csv training data set.
* Please provide the code that creates the csv training data set.

**Comment by jimthompson5802** [comment]
@m-kazuya   This link is to a section in Ludwig's User Guide on image classification, it shows what I wrote about re: `image_path`: https://ludwig-ai.github.io/ludwig-docs/examples/#image-classification

**Comment by m-kazuya** [comment]
@jimthompson5802 Thank you for your reply.
As you said, there was a mistake in image_path. The csv was included some data except for jpg data. 
I can clear the error and create the model!
Thank you once again!
