### ISSUE TITLE
Named Entity Recognition: Can't save a model as SavedModel

### ISSUE THREAD

**Issue by orkenstein** [ludwig-ai/ludwig#1725]
**Describe the bug**
Can't save a savedmodel with `model.save_savedmodel` for NER model:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-fa6d24f46d98> in <module>()
----> 1 model.save_savedmodel("/content")

5 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    697       except Exception as e:  # pylint:disable=broad-except
    698         if hasattr(e, 'ag_error_metadata'):
--> 699           raise e.ag_error_metadata.to_exception(e)
    700         else:
    701           raise

TypeError: Exception encountered when calling layer "sequence_output_feature_1" (type SequenceOutputFeature).

in user code:

    File "/usr/local/lib/python3.7/dist-packages/ludwig/features/base_feature.py", line 260, in call  *
        hidden = self.prepare_decoder_inputs(
    File "/usr/local/lib/python3.7/dist-packages/ludwig/features/base_feature.py", line 486, in prepare_decoder_inputs  *
        feature_hidden = self.output_specific_fully_connected(
    File "/usr/local/lib/python3.7/dist-packages/ludwig/features/base_feature.py", line 446, in output_specific_fully_connected  *
        feature_hidden = tf.reshape(

    TypeError: Failed to convert elements of [-1, None, 256] to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.


Call arguments received:
  • inputs=({'combiner_output': 'tf.Tensor(shape=(None, None, 768), dtype=float32)', 'lengths': 'tf.Tensor(shape=(None,), dtype=int32)'}, {})
  • training=None
  • mask=None
  ```

**To Reproduce**
1. Create a model with config:
```python
config = {
        "input_features": [
            {
                "name": "text",
                "type": "text",
                "level": "word",
                "encoder": "bert",
                "trainable": True,
                "reduce_output": None,
                "preprocessing": {
                  "word_tokenizer": "space"
                }
            }
        ],
        "output_features": [
            {
                "name": "tag",
                "type": "sequence",
                "decoder": "tagger",
            }
        ],
        'training': {
            'batch_size': 32,
            'decay': True,
            'learning_rate': 0.0001,
            'epochs': 10
        }
    }
```
2. Train
3. `model.save_savedmodel("/content")`

Gist and data sample:
https://gist.github.com/orkenstein/29d4e58155584c4cf30b41ce76558b3a

**Expected behavior**
Saved model as Tensorflow SavedModel

**Environment (please complete the following information):**

- Google Colab
- Python 3.7.12
- Ludwig v0.4

**Comment by w4nderlust** [comment]
@orkenstein we are on the verge of releasing v0.5, would you mind checking if the current 0.5rc2 solves this issue already? it won't save as SavedModel as the backend is not TensorFlow anymore, but there are new export options.

**Comment by orkenstein** [comment]
@w4nderlust thank you for letting me know! 
I switched to more manual approach with HuggingFace, so I don't know when i'll be really able to test it.
I'm closing the issue for now.
