### ISSUE TITLE
OSError: [Errno 18] Invalid cross-device link during model training

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig#2229]
**Describe the bug**
When training a model this error appears:
```
  File "/opt/project/ludwig/utils/checkpoint_utils.py", line 137, in save
    os.replace(tmp_path, save_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpr8axnqsy/temp.ckpt' -> '/opt/project/sandbox/custom_stuff/results/experiment_run/model/training_checkpoints/latest.ckpt'

```

To work-around this issue, place files created during training on the same file system as `/tmp`.  E.g., set ludwig training parameter `output_directory="/tmp/results"`

**To Reproduce**

Run docker container with ludwig installed that maps a local disk volume into the container, e.g., ` -v ${PWD}:/opt/project \`, such as
```
docker run -it --rm \
  --name ludwig_torch \
  --user root:root \
  -p 8265:8265 \
  -p 6006:6006 \
  -p 6064:6064 \
  -e PYTHONPATH=/opt/project \
  --entrypoint /bin/bash \
  -v ${PWD}:/opt/project \
  -v ${PWD}/../ludwig-docs:/opt/project-docs \
  -w /opt/project/sandbox/pytest_area \
  ludwig_torch:<tag>
```

Sample Ludwig api code `my_code.py`
```
import logging

import pandas as pd
import numpy as np

from sklearn.datasets import make_regression
from ludwig.api import LudwigModel

if __name__ == "__main__":
    config = {
        "input_features": [
            {"type": "number", "name": "x00"},
            {"type": "number", "name": "x01"},
            {"type": "number", "name": "x02"},
            {"type": "number", "name": "x03"},
            {"type": "number", "name": "x00"},
        ],
        "output_features": [
            {
                "name": "y", "input_size": 5,
                "type": "number",
            },
        ],
        "trainer":{
            "epochs": 5,
        },
    }

    X, y = make_regression(n_samples=2000, n_features=5)
    df = pd.DataFrame(
        np.hstack([X, y.reshape(-1,1)]),
        columns = [f"x{i:02d}" for i in range(5)] + ["y"]
    )
    print(df.head())

    model = LudwigModel(
        config=config,
        logging_level=logging.INFO
    )

    model.experiment(dataset=df)

```

Run the above python program: `python my_code.py`

This is provide full set of error messages
```
Starting with step 0, epoch: 0
Training:  11%|█         | 6/55 [00:00<00:00, 53.31it/s]Traceback (most recent call last):
  File "/opt/project/ludwig/models/trainer.py", line 851, in train
    should_break = self._train_loop(
  File "/opt/project/ludwig/models/trainer.py", line 1016, in _train_loop
    checkpoint_manager.save(progress_tracker.steps)
  File "/opt/project/ludwig/utils/checkpoint_utils.py", line 199, in save
    self.checkpoint.save(save_path, global_step)
  File "/opt/project/ludwig/utils/checkpoint_utils.py", line 137, in save
    os.replace(tmp_path, save_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpr8axnqsy/temp.ckpt' -> '/opt/project/sandbox/custom_stuff/results/experiment_run/model/training_checkpoints/latest.ckpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/sandbox/custom_stuff/custom_loss_and_metric.py", line 370, in <module>
    model.experiment(dataset=df) #, output_directory="/tmp/results")
  File "/opt/project/ludwig/api.py", line 1103, in experiment
    (train_stats, preprocessed_data, output_directory) = self.train(
  File "/opt/project/ludwig/api.py", line 546, in train
    train_stats = trainer.train(
  File "/opt/project/ludwig/models/trainer.py", line 908, in train
    self.model.load_state_dict(torch.load(model_weights_path))
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/project/sandbox/custom_stuff/results/experiment_run/model/model_weights'
Training:  20%|██        | 11/55 [00:00<00:01, 34.49it/s]
```

**Expected behavior**
Successful model experiment run

**Environment (please complete the following information):**

- OS: MacOS 12.4, with Docker Desktop for Mac 4.6.0 (75818)
- Python version: 3.8.13
- Ludwig version: 0.5.1 and 0.5.3

**Additional context**
This error appears to be connected to a recent change that affected this section of code:
https://github.com/ludwig-ai/ludwig/blob/9d7da5f68ad879f6c7296d8df25a4c6b83937354/ludwig/utils/checkpoint_utils.py#L125-L132

This change requires the temporary checkpoint dataset and location of the `output_directory` to be on the same file system.  

In the container setup that encountered the error, the two are on different filesystems within the container:
```
root@c3fda044d5d6:/opt/project/sandbox/pytest_area# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         133G   48G   79G  38% /              #<=location of /tmp
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
grpcfuse        932G  465G  468G  50% /opt/project    #<=the default location for output_directory
/dev/vda1       133G   48G   79G  38% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /sys/firmware
```

Not sure if there is a code fix for this.  May require updated documentation indicating the requirement for the location `output_directory` to be on the same filesystem as `/tmp`.

**Comment by justinxzhao** [comment]
@jimthompson5802, @dantreiman has put together a fix for this error in #2225.

Would you be able to check that Daniel's PR fixes this issue for you?

**Comment by jimthompson5802** [comment]
@justinxzhao  Thanks for the pointer.  I tested @dantreiman  PR #2225 and it fixed the issue for me.  LGTM.

**Comment by dantreiman** [comment]
Merged https://github.com/ludwig-ai/ludwig/pull/2225, closing
