### ISSUE TITLE
Unable to resume training

### ISSUE THREAD

**Issue by noahlh** [ludwig-ai/ludwig#2287]
Training seems to be working, but I'm loathe to start a ~15-hour training run before I can confirm that resuming is working, and it seems to not be working :(

I'm starting the training a fresh directory (no /results subfolder) with:

`ludwig train --dataset db/normalized_lots.json -c normalized_lots.yaml --experiment_name normalized_lots -mrp results/normalized_lots_run/`

And all is well.  If I cancel the run after some training has completed and try that same command again, I get the following exception:

```python
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/models/trainer.py", line 851, in train
    should_break = self._train_loop(
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/models/trainer.py", line 990, in _train_loop
    loss, all_losses = self.train_step(
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/models/trainer.py", line 283, in train_step
    self.optimizer.step()
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/optim/adam.py", line 157, in step
    adam(params_with_grad,
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/optim/adam.py", line 213, in adam
    func(params,
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/optim/adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nlh/.pyenv/versions/3.10.5/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/cli.py", line 164, in main
    CLI()
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/cli.py", line 69, in train
    train.cli(sys.argv[2:])
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/train.py", line 387, in cli
    train_cli(**vars(args))
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/train.py", line 181, in train_cli
    model.train(
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/api.py", line 546, in train
    train_stats = trainer.train(
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ludwig/models/trainer.py", line 908, in train
    self.model.load_state_dict(torch.load(model_weights_path))
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/nlh/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/normalized_lots_run/model/model_weights'
```

Any thoughts or help would be appreciated!

**Environment**

- OS: Ubuntu
- Version 22.04
- Python version 3.10.5
- Ludwig version 0.5.4

**Comment by tgaddair** [comment]
Awesome, thanks @noahlh. Glad to hear this is not a hard blocker for now.
