### ISSUE TITLE
Metadata mismatch while calculating overall stats

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2308]
On occassion, I see the following error in `model.evaluate()` while computing overall stats using a sample of the dataframe. I haven't been able to reproduce this error consistently, but it does surface from time to time. 

This was seen while training a small image dataset with only 1 image input feature and a categorical output feature.

```
Full computation of stats only supported for pandas dataframes. Sampling the first 10000 rows of the feature and target dataframes for computing overall stats.
Traceback (most recent call last):
  File "/home/ray/train_ispy2.py", line 145, in <module>
    app()
  File "/home/ray/train_ispy2.py", line 126, in app
    eval_stats, train_stats, _, _ = model.experiment(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/api.py", line 1147, in experiment
    eval_stats, _, _ = self.evaluate(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/api.py", line 912, in evaluate
    overall_stats = calculate_overall_stats(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/models/predictor.py", line 309, in calculate_overall_stats
    feature_df = feature_df.head(n=STATS_SAMPLE_SIZE, npartitions=-1, compute=True)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/dataframe/core.py", line 1219, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/dataframe/core.py", line 1253, in _head
    result = result.compute()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/base.py", line 312, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/dask/scheduler.py", line 202, in ray_dask_get
    result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/dask/scheduler.py", line 503, in ray_get_unpack
    computed_result = get_result(object_refs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/dask/scheduler.py", line 490, in get_result
    return ray.get(object_refs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::dask:('head-200-10000-rename-814aae6336586f7ac43cb63c641e157b', 0) (pid=22528, ip=192.168.13.44)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:('head-partial-10000-rename-814aae6336586f7ac43cb63c641e157b', 156) (pid=22280, ip=192.168.13.44)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:('block_to_df-rename-814aae6336586f7ac43cb63c641e157b', 156) (pid=22276, ip=192.168.13.44)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/dask/scheduler.py", line 431, in dask_task_wrapper
    result = func(*actual_args)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/dask/dataframe/utils.py", line 400, in check_meta
    raise ValueError(
ValueError: Metadata mismatch found in `from_delayed`.
```

**Comment by arnavgarg1** [comment]
Update: This might be an issue on Ray's end - https://docs.ray.io/en/latest/_modules/ray/data/dataset.html#Dataset.to_dask 

@arnavgarg1 to create an reproducible script for this error and then create an issue on Ray's GitHub to get this fixed. In the mean time, we might be manually able to override/customize the `dask.from_delayed` call to get past this issue.

**Comment by arnavgarg1** [comment]
@geoffreyangus found that this issue arises because of empty partitions after splitting the dataset. @geoffreyangus will create a follow-up PR to address this
