### ISSUE TITLE
Mnist example: FileNotFoundError: [Errno 2] No such file or directory: 'ludwig/examples/mnist/results/simple_image_experiment_single_model/model/model_weights'

### ISSUE THREAD

**Issue by andife** [ludwig-ai/ludwig#2339]
**Describe the bug**

**To Reproduce**
Running:

/local_data/andife/ludwig/examples/mnist$ python simple_model_training.py

produces

`Traceback (most recent call last):
  File "simple_model_training.py", line 29, in <module>
    (train_stats, _, output_directory) = model.train(  # training statistics  # location for training results saved to disk
  File "/local_data/andife/miniforge3/envs/ludwignew/lib/python3.8/site-packages/ludwig/api.py", line 546, in train
    train_stats = trainer.train(
  File "/local_data/andife/miniforge3/envs/ludwignew/lib/python3.8/site-packages/ludwig/models/trainer.py", line 908, in train
    self.model.load_state_dict(torch.load(model_weights_path))
  File "/local_data/andife/miniforge3/envs/ludwignew/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/local_data/andife/miniforge3/envs/ludwignew/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/local_data/andife/miniforge3/envs/ludwignew/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/local_data/andife/ludwig/examples/mnist/results/simple_image_experiment_single_model/model/model_weights'
`

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
Working example

**Screenshots**

**Environment (please complete the following information):**

- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version: 3.8
- Ludwig version: ludwig 0.5.4

**Comment by binbinmeng** [comment]
@andife how did you solved this issue ? I met the same errors.

**Comment by andife** [comment]
I do not really know...  I created another conda-environment and installed ludwig again... and it runs...
