### ISSUE TITLE
 [Question] Best practice to use remote storage

### ISSUE THREAD

**Issue by Jeffwan** [ludwig-ai/ludwig#2361]
I am using input file in S3 or HDFS. I am trying to understand any tricks using dataset in remote store. 

I notice ludwig CLi like `init_config` etc read data file, the preprocessing and training part, the ray cluster reads file as well. 

1. does ludwig operation like `init_config` underneath use ray dataset as well? I didn't see s3 or hdfs protocol support in ludwig code base, I assume Ray plays the role here?

2. If I use remote Ray cluster as executor and ludwig program as the driver. Using S3 as an example, I think I should set AWS env in both side? 

3. Maybe it's a good idea to support dumping config file directly in S3 so we do not need to copy file to remote any more.

```
ludwig init_config --dataset s3://ludwig-automl/rotten_tomatoes.csv --target=recommended --hyperopt=true --time_limit_s=300 --output s3://ludwig-automl/rotten_tomatoes.yaml
NumExpr defaulting to 8 threads.
/usr/local/lib/python3.8/site-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(
███████████████████████
█ █ █ █  ▜█ █ █ █ █   █
█ █ █ █ █ █ █ █ █ █ ███
█ █   █ █ █ █ █ █ █ ▌ █
█ █████ █ █ █ █ █ █ █ █
█     █  ▟█     █ █   █
███████████████████████
ludwig v0.6.dev - Init Config

Initializing new Ray cluster...
2022-08-08 18:54:36,720	INFO services.py:1470 -- View the Ray dashboard at http://127.0.0.1:8265
2022-08-08 18:54:36,769	WARNING services.py:2002 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=4.81gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
Found credentials in environment variables.
.......
Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 166, in main
    CLI()
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 66, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 151, in init_config
    automl.cli_init_config(sys.argv[2:])
  File "/usr/local/lib/python3.8/site-packages/ludwig/automl/automl.py", line 414, in cli_init_config
    init_config(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/ludwig/automl/automl.py", line 341, in init_config
    with open(output, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 's3://ludwig-automl/rotten_tomatoes.yaml'
```

**Comment by tgaddair** [comment]
Hey @Jeffwan, good questions:

1. For most of these filesystem operations, we use [fsspec](https://filesystem-spec.readthedocs.io/en/latest/), which provides an abstraction over s3, gcs, hdfs, etc. When reading with Ray Datasets, we use the [FSSpecHandler](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/dataset/ray.py#L62) to allow Ray to read from any remote object storage.
2. I usually mount credentials in both the head and workers, but it should only be needed on the head node / driver. Dask and Ray Datasets should be able to propagate the credentials to the workers when needed for loading file chunks.
3.  Looks like this particular line was an oversight, it should be using the [open_file](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/utils/fs_utils.py#L219) helper function instead of the native Python `open`. I'll make a PR to fix this.

**Comment by tgaddair** [comment]
@Jeffwan #2364 should hopefully this the issue by allowing you to write `init_config` results to s3.
