### ISSUE TITLE
Learning rate tuning failure in tests/integration_tests/test_ray.py::test_tune_batch_size_lr 

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2458]
```
(tune_learning_rate_fn pid=58056) Explored learning_rate=1.731410312890155e-08 loss=1.310225486755371
(tune_learning_rate_fn pid=58056) Explored learning_rate=2.9597020956312317e-08 loss=1.315243124961853
(tune_learning_rate_fn pid=58056) Failed to detect optimal learning rate
(tune_learning_rate_fn pid=58056) Traceback (most recent call last):
(tune_learning_rate_fn pid=58056)   File "/workspaces/ludwig/ludwig/trainers/trainer.py", line 367, in get_optimal_lr
(tune_learning_rate_fn pid=58056)     best_lr_index = np.gradient(loss).argmin() + skip_begin
(tune_learning_rate_fn pid=58056)   File "<__array_function__ internals>", line 180, in gradient
(tune_learning_rate_fn pid=58056)   File "/usr/local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1219, in gradient
(tune_learning_rate_fn pid=58056)     raise ValueError(
(tune_learning_rate_fn pid=58056) ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
(tune_learning_rate_fn pid=58056) Could not determine optimal learning rate, falling back to base default
(tune_learning_rate_fn pid=58056) Selected learning_rate=0.001
```

**Comment by arnavgarg1** [comment]
This is the intended behavior, closing.
