### ISSUE TITLE
encoder bug: missing argument `max_sequence_length` for RoBERTa encoder

### ISSUE THREAD

**Issue by rudolfolah** [ludwig-ai/ludwig#2851]
**Describe the bug**
Cannot use the RoBERTa encoder for input and output features.

**To Reproduce**
Configuration of model to reproduce the issue:

```python
config = {
    "input_features": [
        {
            "name": "source_code",
            "type": "text",
            "encoder": {
                "type": "roberta",
                "max_sequence_length": 3000,
            }
        },
    ],
    "output_features": [
        {
            "name": "test_code",
            "type": "text",
            "encoder": {
                "type": "roberta",
                "max_sequence_length": 1000,
            }
        }
    ],
}
```

The training data used:

```
source_code,test_code
function addOne(a) { return a + 1 },expect(addOne(1)).toEqual(2)
function hello(a) { return 1+a },expect(hello(1)).toEqual(2)
```

**Expected behavior**
The model can be trained with the RoBERTa encoder and the `max_sequence_length` argument is passed through and can be adjusted through the features encoder configuration.

**Environment:**

- OS: macOS 12.6
- Version \[e.g. 22\]
- Python version 3.9
- Ludwig version 0.6.4

**Additional context**
The `"max_sequence_length"` was added to the configuration to try to fix the issue, when changing the encoder to "bert" the configuration worked so it seems an issue with this particular encoder.

Traceback:

```
Traceback (most recent call last):
  File "/Users/rudolfo/Workspace/ludwig-code-gen/main.py", line 27, in <module>
    model.train(
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/api.py", line 505, in train
    self.model = LudwigModel.create_model(self.config, random_seed=random_seed)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/api.py", line 1542, in create_model
    return model_type(**config, random_seed=random_seed)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/models/ecd.py", line 46, in __init__
    self.input_features.update(self.build_inputs(self._input_features_def))
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/models/base.py", line 55, in build_inputs
    input_features[input_feature_def[NAME]] = cls.build_single_input(input_feature_def, input_features)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/models/base.py", line 72, in build_single_input
    input_feature_obj = input_feature_class(input_feature_def, encoder_obj=encoder_obj)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/features/text_feature.py", line 188, in __init__
    super().__init__(input_feature_config, encoder_obj=encoder_obj, **kwargs)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/features/sequence_feature.py", line 271, in __init__
    self.encoder_obj = self.initialize_encoder(input_feature_config.encoder)
  File "/Users/rudolfo/Workspace/ludwig-code-gen/env/lib/python3.9/site-packages/ludwig/features/base_feature.py", line 170, in initialize_encoder
    return encoder_cls(encoder_config=encoder_config, **encoder_params_dict)
TypeError: __init__() missing 1 required positional argument: 'max_sequence_length'
```

**Comment by arnavgarg1** [comment]
Hi @rudolfolah, thanks for flagging this problem! I think this is something we've missed!

Would you be interested in making a contribution?

It would just require adding a new `max_sequence_length` as a new type in the Dataclass here: https://github.com/ludwig-ai/ludwig/blob/master/ludwig/schema/encoders/text_encoders.py#L1176

You can take a look at the other encoder classes in this file as reference :) 

If not, we'll add it in today and it should be available on Ludwig master for you to use by end of day. Let us know!

**Comment by rudolfolah** [comment]
@arnavgarg1 awesome, just opened the PR and checked whether there's already test coverage 👍

**Comment by arnavgarg1** [comment]
Perfect, thanks @rudolfolah. Just approved :) Congrats on making your first contribution!

**Comment by arnavgarg1** [comment]
@rudolfolah One thing I wanted to call out is that we currently don't support `max_sequence_length` for text output feature types. That attribute is only supported for text input features.
