### ISSUE TITLE
Preprocessing audio feature with sample ratio fails

### ISSUE THREAD

**Issue by Peetee06** [ludwig-ai/ludwig#2995]
**Describe the bug**
I'm trying to train a model on audio features using a sample ratio as suggested by @justinxzhao [here](https://github.com/ludwig-ai/ludwig/discussions/2943). At the start of preprocessing I get `KeyError: 0` from pandas. 

Here is the output:

```bash
╒═══════════════╕
│ LUDWIG CONFIG │
╘═══════════════╛

{   'combiner': {   'activation': 'relu',
                    'bias_initializer': 'zeros',
                    'dropout': 0.0,
                    'fc_layers': None,
                    'flatten_inputs': False,
                    'norm': None,
                    'norm_params': None,
                    'num_fc_layers': 0,
                    'output_size': 256,
                    'residual': False,
                    'type': 'concat',
                    'use_bias': True,
                    'weights_initializer': 'xavier_uniform'},
    'defaults': {   'audio': {   'preprocessing': {   'audio_file_length_limit_in_s': 7.5,
                                                      'computed_fill_value': None,
                                                      'fill_value': None,
                                                      'in_memory': True,
                                                      'missing_value_strategy': 'bfill',
                                                      'norm': None,
                                                      'num_fft_points': None,
                                                      'num_filter_bands': 80,
                                                      'padding_value': 0.0,
                                                      'type': 'fbank',
                                                      'window_length_in_s': 0.04,
                                                      'window_shift_in_s': 0.02,
                                                      'window_type': 'hamming'}},
                    'bag': {   'preprocessing': {   'computed_fill_value': '<UNK>',
                                                    'fill_value': '<UNK>',
                                                    'lowercase': False,
                                                    'missing_value_strategy': 'fill_with_const',
                                                    'most_common': 10000,
                                                    'tokenizer': 'space'}},
                    'binary': {   'preprocessing': {   'computed_fill_value': None,
                                                       'fallback_true_label': None,
                                                       'fill_value': None,
                                                       'missing_value_strategy': 'fill_with_false'}},
                    'category': {   'preprocessing': {   'computed_fill_value': '<UNK>',
                                                         'fill_value': '<UNK>',
                                                         'lowercase': False,
                                                         'missing_value_strategy': 'fill_with_const',
                                                         'most_common': 10000}},
                    'date': {   'preprocessing': {   'computed_fill_value': '',
                                                     'datetime_format': None,
                                                     'fill_value': '',
                                                     'missing_value_strategy': 'fill_with_const'}},
                    'h3': {   'preprocessing': {   'computed_fill_value': 576495936675512319,
                                                   'fill_value': 576495936675512319,
                                                   'missing_value_strategy': 'fill_with_const'}},
                    'image': {   'preprocessing': {   'computed_fill_value': None,
                                                      'fill_value': None,
                                                      'height': None,
                                                      'in_memory': True,
                                                      'infer_image_dimensions': True,
                                                      'infer_image_max_height': 256,
                                                      'infer_image_max_width': 256,
                                                      'infer_image_num_channels': True,
                                                      'infer_image_sample_size': 100,
                                                      'missing_value_strategy': 'bfill',
                                                      'num_channels': None,
                                                      'num_processes': 1,
                                                      'resize_method': 'interpolate',
                                                      'scaling': 'pixel_normalization',
                                                      'width': None}},
                    'number': {   'preprocessing': {   'computed_fill_value': 0.0,
                                                       'fill_value': 0.0,
                                                       'missing_value_strategy': 'fill_with_const',
                                                       'normalization': None}},
                    'sequence': {   'preprocessing': {   'computed_fill_value': '<UNK>',
                                                         'fill_value': '<UNK>',
                                                         'lowercase': False,
                                                         'max_sequence_length': 256,
                                                         'missing_value_strategy': 'fill_with_const',
                                                         'most_common': 20000,
                                                         'padding': 'right',
                                                         'padding_symbol': '<PAD>',
                                                         'tokenizer': 'space',
                                                         'unknown_symbol': '<UNK>',
                                                         'vocab_file': None}},
                    'set': {   'preprocessing': {   'computed_fill_value': '<UNK>',
                                                    'fill_value': '<UNK>',
                                                    'lowercase': False,
                                                    'missing_value_strategy': 'fill_with_const',
                                                    'most_common': 10000,
                                                    'tokenizer': 'space'}},
                    'text': {   'preprocessing': {   'computed_fill_value': '<UNK>',
                                                     'fill_value': '<UNK>',
                                                     'lowercase': True,
                                                     'max_sequence_length': 256,
                                                     'missing_value_strategy': 'fill_with_const',
                                                     'most_common': 20000,
                                                     'padding': 'right',
                                                     'padding_symbol': '<PAD>',
                                                     'pretrained_model_name_or_path': None,
                                                     'tokenizer': 'space_punct',
                                                     'unknown_symbol': '<UNK>',
                                                     'vocab_file': None}},
                    'timeseries': {   'preprocessing': {   'computed_fill_value': '',
                                                           'fill_value': '',
                                                           'missing_value_strategy': 'fill_with_const',
                                                           'padding': 'right',
                                                           'padding_value': 0.0,
                                                           'timeseries_length_limit': 256,
                                                           'tokenizer': 'space'}},
                    'vector': {   'preprocessing': {   'computed_fill_value': '',
                                                       'fill_value': '',
                                                       'missing_value_strategy': 'fill_with_const',
                                                       'vector_size': None}}},
    'input_features': [   {   'column': 'audio_path',
                              'encoder': {'type': 'parallel_cnn'},
                              'name': 'audio_path',
                              'preprocessing': {   'audio_file_length_limit_in_s': 1.0,
                                                   'norm': 'per_file',
                                                   'num_filter_bands': 80,
                                                   'type': 'fbank',
                                                   'window_length_in_s': 0.025,
                                                   'window_shift_in_s': 0.01},
                              'proc_column': 'audio_path_AUNI5p',
                              'tied': None,
                              'type': 'audio'}],
    'ludwig_version': '0.6',
    'model_type': 'ecd',
    'output_features': [   {   'column': 'label',
                               'decoder': {'type': 'classifier'},
                               'dependencies': [],
                               'loss': {   'class_similarities_temperature': 0,
                                           'class_weights': None,
                                           'confidence_penalty': 0.0,
                                           'robust_lambda': 0,
                                           'type': 'softmax_cross_entropy',
                                           'weight': 1.0},
                               'name': 'label',
                               'num_classes': 2,
                               'preprocessing': {   'missing_value_strategy': 'drop_row'},
                               'proc_column': 'label_mZFLky',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'oversample_minority': None,
                         'sample_ratio': 0.3,
                         'split': {   'probabilities': [0.7, 0.1, 0.2],
                                      'type': 'random'},
                         'undersample_majority': None},
    'trainer': {   'batch_size': 128,
                   'checkpoints_per_epoch': 0,
                   'decay': False,
                   'decay_rate': 0.96,
                   'decay_steps': 10000,
                   'early_stop': -1,
                   'epochs': 300,
                   'eval_batch_size': None,
                   'evaluate_training_set': True,
                   'gradient_clipping': {   'clipglobalnorm': 0.5,
                                            'clipnorm': None,
                                            'clipvalue': None},
                   'increase_batch_size_eval_metric': 'loss',
                   'increase_batch_size_eval_split': 'training',
                   'increase_batch_size_on_plateau': 0,
                   'increase_batch_size_on_plateau_max': 512,
                   'increase_batch_size_on_plateau_patience': 5,
                   'increase_batch_size_on_plateau_rate': 2.0,
                   'learning_rate': 0.001,
                   'learning_rate_scaling': 'linear',
                   'learning_rate_warmup_epochs': 1.0,
                   'optimizer': {   'amsgrad': False,
                                    'betas': (0.9, 0.999),
                                    'eps': 1e-08,
                                    'lr': 0.001,
                                    'type': 'adam',
                                    'weight_decay': 0.0},
                   'reduce_learning_rate_eval_metric': 'loss',
                   'reduce_learning_rate_eval_split': 'training',
                   'reduce_learning_rate_on_plateau': 0.0,
                   'reduce_learning_rate_on_plateau_patience': 5,
                   'reduce_learning_rate_on_plateau_rate': 0.5,
                   'regularization_lambda': 0.0,
                   'regularization_type': 'l2',
                   'should_shuffle': True,
                   'staircase': False,
                   'steps_per_checkpoint': 0,
                   'train_steps': None,
                   'type': 'trainer',
                   'validation_field': 'combined',
                   'validation_metric': 'loss'}}

╒═══════════════╕
│ PREPROCESSING │
╘═══════════════╛

Using full dataframe
Building dataset (it may take a while)
Traceback (most recent call last):
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1032, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1039, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/train.py", line 81, in <module>
    train()
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "src/train.py", line 64, in train
    model.train(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/api.py", line 449, in train
    preprocessed_data = self.preprocess(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/api.py", line 1294, in preprocess
    preprocessed_data = preprocess_for_training(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 1621, in preprocess_for_training
    processed = data_format_processor.preprocess_for_training(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 234, in preprocess_for_training
    return _preprocess_df_for_training(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 1828, in _preprocess_df_for_training
    data, training_set_metadata = build_dataset(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 1166, in build_dataset
    metadata = build_metadata(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 1313, in build_metadata
    metadata[feature_name] = get_from_registry(feature_config[TYPE], base_type_registry).get_feature_meta(
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/ludwig/features/audio_feature.py", line 112, in get_feature_meta
    first_audio_file_path = column.head(1)[0]
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/pandas/core/series.py", line 989, in _get_value
    loc = self.index.get_loc(label)
  File "/home/trost/miniconda3/envs/mlflow-95b8fe275e9987dafa102b0ee13278631dbef1f5/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

I use following config:

```yaml
preprocessing:
  sample_ratio: 0.1
input_features:
  - name: audio_path
    type: audio
    preprocessing:
      audio_file_length_limit_in_s: 1.0
      type: fbank
      window_length_in_s: 0.025
      window_shift_in_s: 0.01
      num_filter_bands: 80
      norm: per_file
output_features:
  - name: label
    type: category
    num_classes: 2
trainer:
  epochs: 300
  early_stop: -1
```

Also fails for sample_ratio of 0.3 and 0.5.
It works for 1.0 and when removing sample_ratio from config.

**Comment by dalianaliu** [comment]
We are taking a look at the issue.

**Comment by justinxzhao** [comment]
Hi @Peetee06,

Thanks for filing the issue. It turns out it's a one-line fix in `audio_feature.py`: https://github.com/ludwig-ai/ludwig/pull/3006.

If you would like to try out the fix (I expect the PR to land later today), then you'll have to install Ludwig from head.

Please let me know if you have more trouble!

```
git@github.com:ludwig-ai/ludwig.git
cd ludwig
pip install -e .
```

**Comment by Peetee06** [comment]
Works like a charm now. Thanks for the fix!
