### ISSUE TITLE
Errors in Ludwig Docker Images

### ISSUE THREAD

**Issue by Velyn-N** [ludwig-ai/ludwig#3182]
**Describe the bug**
When using the Docker Image `ludwigai:ludwig-gpu:master` to start a ludwig container an error is thrown. It says that PyTorch and TorchAudio were compiled with different CUDA Versions.
When using the Docker Image `ludwigai:ludwig:master` or `ludwigai:ludwig-ray:master` another error is thrown, this one says no module named 'mlflow' was found.

**To Reproduce**
Follow the Steps from the Docker Section in the Getting Started Guide on ludwig.ai Website ([Link](https://ludwig.ai/latest/getting_started/docker/))

I used a slightly modified version of the Command from "[Run Ludwig CLI Section](https://ludwig.ai/latest/getting_started/docker/#run-ludwig-cli)" as you can see in the logs below. I mostly changed the paths to the ones of my system. I tried it with `train` and `experiment` command as entrypoint. I tried different versions of the paths too.

I used the data and config from the Rotten Tomatoes Example found in the Guide.
Data: [Link](https://ludwig.ai/latest/getting_started/prepare_data/)
Config: [Link](https://ludwig.ai/latest/getting_started/train/)

**Expected behavior**
Ludwig should train itself.

**Screenshots** (In this case its logs)
Here is the full Error from ludwig-gpu image:
```
docker run -v /mnt/z/Development/MachineLearning/Ludwig/Rotten_Tomatoes/data:/data  \
    -v /mnt/z/Development/MachineLearning/Ludwig/Rotten_Tomatoes/src:/src \
    ludwigai/ludwig-gpu:master \
    train --config /src/config.yaml \
        --dataset /data/rotten_tomatoes.csv \
        --output_directory /src/results
Traceback (most recent call last):
  File "/opt/conda/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 172, in main
    CLI()
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 67, in __init__
    getattr(self, args.command)()
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 70, in train
    from ludwig import train
  File "/opt/conda/lib/python3.10/site-packages/ludwig/train.py", line 23, in <module>
    from ludwig.api import LudwigModel
  File "/opt/conda/lib/python3.10/site-packages/ludwig/api.py", line 40, in <module>
    from ludwig.backend import Backend, initialize_backend, provision_preprocessing_workers
  File "/opt/conda/lib/python3.10/site-packages/ludwig/backend/__init__.py", line 22, in <module>
    from ludwig.backend.base import Backend, LocalBackend
  File "/opt/conda/lib/python3.10/site-packages/ludwig/backend/base.py", line 29, in <module>
    from ludwig.data.cache.manager import CacheManager
  File "/opt/conda/lib/python3.10/site-packages/ludwig/data/cache/manager.py", line 8, in <module>
    from ludwig.data.dataset.base import DatasetManager
  File "/opt/conda/lib/python3.10/site-packages/ludwig/data/dataset/base.py", line 21, in <module>
    from ludwig.utils.defaults import default_random_seed
  File "/opt/conda/lib/python3.10/site-packages/ludwig/utils/defaults.py", line 24, in <module>
    from ludwig.features.feature_registries import get_input_type_registry
  File "/opt/conda/lib/python3.10/site-packages/ludwig/features/feature_registries.py", line 33, in <module>
    from ludwig.features.audio_feature import AudioFeatureMixin, AudioInputFeature
  File "/opt/conda/lib/python3.10/site-packages/ludwig/features/audio_feature.py", line 22, in <module>
    import torchaudio
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/_extension.py", line 136, in <module>
    _check_cuda_version()
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/_extension.py", line 128, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.6 whereas TorchAudio has CUDA version 11.7. Please install the TorchAudio version that matches your PyTorch version.
```

Here is the full error from `ludwig` image:
```
docker run -v /mnt/z/Development/MachineLearning/Ludwig/Rotten_Tomatoes/data:/data  \
    -v /mnt/z/Development/MachineLearning/Ludwig/Rotten_Tomatoes/src:/src \
    ludwigai/ludwig:master \
    train --config /src/config.yaml \
        --dataset /data/rotten_tomatoes.csv \
        --output_directory /src/results
Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 172, in main
    CLI()
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 67, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.8/site-packages/ludwig/cli.py", line 72, in train
    train.cli(sys.argv[2:])
  File "/usr/local/lib/python3.8/site-packages/ludwig/train.py", line 379, in cli
    add_contrib_callback_args(parser)
  File "/usr/local/lib/python3.8/site-packages/ludwig/contrib.py", line 27, in add_contrib_callback_args
    const=contrib_cls(),
  File "/usr/local/lib/python3.8/site-packages/ludwig/contribs/mlflow/__init__.py", line 42, in __init__
    self.tracking_uri = mlflow.get_tracking_uri()
  File "/usr/local/lib/python3.8/site-packages/ludwig/utils/package_utils.py", line 34, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.8/site-packages/ludwig/utils/package_utils.py", line 23, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mlflow'
```

**Environment (please complete the following information):**

- OS: Windows
- Version 11
- Python 3.10.2 (on Windows, so not applicable here i guess?)
- Ludwig 0.7.1

I use Docker Desktop with WSL2 Engine as my Docker environment. It runs the latest version (Docker Desktop 4.16.3 (96739)).
I executed the bash commands in my WSL2 shell. I run Ubuntu 20.04.5 LTS there.
When using the Windows cmd for the `docker run` command it did not work either.

**Comment by tgaddair** [comment]
Hey @Velyn-N, thanks for reporting this issue. Definitely looks like there's an issue with the latest docker image versions we published. We'll try to get this fixed and push new images as soon as possible.

**Comment by Velyn-N** [comment]
Thank you very much for looking into this so quickly! 😀

**Comment by tgaddair** [comment]
Absolutely! From testing locally, I believe #3186 should address the issue. We should be able to land it and cut a new release within the next day.

**Comment by tgaddair** [comment]
Hey @Velyn-N, we just released v0.7.2, which should contain fixes for all docker images. Let me know if you still run into any issues. Thanks!

**Comment by Velyn-N** [comment]
I tried the new Version and it worked flawlessly! Thank you very much.

**Comment by tgaddair** [comment]
Excellent! Thanks for verifying.
