### ISSUE TITLE
Named Entity Recognition Tagging

### ISSUE THREAD

**Issue by giurlanda** [ludwig-ai/ludwig#3273]
**Describe the bug**
I'm using ludwig 0.7 and I had some problems to reproduce the  [Named Entity Recognition Tagging](https://ludwig.ai/0.7/examples/ner_tagging/) exactly as it is.

I had already used ludwig 0.6 and I didn't have any problem with the same example.

**To Reproduce**
Follow the tutorial  [Named Entity Recognition Tagging](https://ludwig.ai/0.7/examples/ner_tagging/) 
```
input_features:
    -
        name: utterance
        type: text
        encoder: 
            type: rnn
            cell_type: lstm
            reduce_output: null
        preprocessing:
          tokenizer: space

output_features:
    -
        name: tag
        type: sequence
        decoder: 
            type: tagger
```

**Environment (please complete the following information):**

- OS: Ubuntu 20.04.5 LTS
- Python 3.8.10
- Ludwig 0.7.3

**Additional context**
```
$ ludwig experiment --dataset data/sequence_tags.csv --config src/config.yml
███████████████████████
█ █ █ █  ▜█ █ █ █ █   █
█ █ █ █ █ █ █ █ █ █ ███
█ █   █ █ █ █ █ █ █ ▌ █
█ █████ █ █ █ █ █ █ █ █
█     █  ▟█     █ █   █
███████████████████████
ludwig v0.7.3 - Experiment


╒════════════════════════╕
│ EXPERIMENT DESCRIPTION │
╘════════════════════════╛

╒══════════════════╤══════════════════════════════════════════════════════════════════════════╕
│ Experiment name  │ experiment                                                               │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Model name       │ run                                                                      │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Output directory │ /home/projects/test/results/experiment_run                           │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ ludwig_version   │ '0.7.3'                                                                  │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ command          │ ('/home/projects/names/.venv/bin/ludwig experiment --dataset '       │
│                  │  'data/sequence_tags.csv --config src/config.yml')                       │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ random_seed      │ 42                                                                       │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ dataset          │ 'data/sequence_tags.csv'                                                 │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ data_format      │ 'csv'                                                                    │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ torch_version    │ '2.0.0+cu117'                                                            │
├──────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ compute          │ {'gpu_type': 'Tesla V100-DGXS-32GB', 'gpus_per_node': 4, 'num_nodes': 1} │
╘══════════════════╧══════════════════════════════════════════════════════════════════════════╛

╒═══════════════╕
│ LUDWIG CONFIG │
╘═══════════════╛

User-specified config (with upgrades):

{   'input_features': [   {   'encoder': {   'cell_type': 'lstm',
                                             'reduce_output': None,
                                             'type': 'rnn'},
                              'name': 'utterance',
                              'preprocessing': {'tokenizer': 'space'},
                              'type': 'text'}],
    'ludwig_version': '0.7.3',
    'output_features': [   {   'decoder': {'type': 'tagger'},
                               'name': 'tag',
                               'type': 'sequence'}]}

Full config saved to:
/home/projects/test/results/experiment_run/experiment/model/model_hyperparameters.json

╒═══════════════╕
│ PREPROCESSING │
╘═══════════════╛

Using full raw dataset, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Max length of feature 'utterance': 15 (without start and stop symbols)
Setting max length using dataset: 17 (including start and stop symbols)
max sequence length is 17 for feature 'utterance'
Max length of feature 'tag': 15 (without start and stop symbols)
Setting max length using dataset: 17 (including start and stop symbols)
max sequence length is 17 for feature 'tag'
Building dataset: DONE
Writing preprocessed training set cache
Writing preprocessed test set cache
Writing preprocessed validation set cache
Writing train set metadata
Validation set empty. If this is unintentional, please check the preprocessing configuration.
Test set empty. If this is unintentional, please check the preprocessing configuration.

Dataset Statistics
╒═══════════╤═══════════════╤════════════════════╕
│ Dataset   │   Size (Rows) │ Size (In Memory)   │
╞═══════════╪═══════════════╪════════════════════╡
│ Training  │             3 │ 848 b              │
╘═══════════╧═══════════════╧════════════════════╛

╒═══════╕
│ MODEL │
╘═══════╛

Warnings and other logs:
  embedding_size (256) is greater than vocab_size (39). Setting embedding size to be equal to vocab_size.
Created a temporary directory at /tmp/tmpgqkyhtak
Writing /tmp/tmpgqkyhtak/_remote_module_non_scriptable.py
Tuning batch size...
Tuning batch size...
Batch size 2 is invalid, must be less than or equal to 20.0% dataset size (0 samples of 3) and less than or equal to max batch size 1099511627776
Could not tune batch size, using minimum batch size of 2
Selected batch_size=2

╒══════════╕
│ TRAINING │
╘══════════╛

Creating fresh model training run.
Training for 200 step(s), approximately 100 epoch(s).
Early stopping policy: 5 round(s) of evaluation, or 10 step(s), approximately 5 epoch(s).

Starting with step 0, epoch: 0
Training:   0%|                                                                                                                                     | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/projects/names/.venv/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/cli.py", line 178, in main
    CLI()
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/cli.py", line 68, in __init__
    getattr(self, args.command)()
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/cli.py", line 88, in experiment
    experiment.cli(sys.argv[2:])
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/experiment.py", line 528, in cli
    experiment_cli(**vars(args))
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/experiment.py", line 217, in experiment_cli
    (eval_stats, train_stats, preprocessed_data, output_directory) = model.experiment(
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/api.py", line 1204, in experiment
    (train_stats, preprocessed_data, output_directory) = self.train(
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/api.py", line 629, in train
    train_stats = trainer.train(
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/trainers/trainer.py", line 687, in train
    should_break = self._train_loop(
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/trainers/trainer.py", line 794, in _train_loop
    loss, all_losses = self.train_step(
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/trainers/trainer.py", line 261, in train_step
    model_outputs = self.dist_model((inputs, targets))
  File "/home/projects/names/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/models/ecd.py", line 143, in forward
    return self.decode(combiner_outputs, targets, mask)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/models/ecd.py", line 96, in decode
    decoder_outputs = output_feature(combiner_outputs, output_last_hidden, mask=mask, target=target)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/features/base_feature.py", line 399, in forward
    logits = self.logits(logits_input, target=target)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/features/sequence_feature.py", line 344, in logits
    return self.decoder_obj(inputs, target=target)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/projects/names/.venv/lib/python3.8/site-packages/ludwig/decoders/sequence_tagger.py", line 60, in forward
    raise ValueError(
ValueError: Decoder inputs rank is 2, but should be 3: [batch_size x max_sequence_length x hidden_size] in when using a tagger sequential decoder. Consider setting reduce_output to None if a sequential encoder / combiner is used.
Training:   0%|                                                                                                                                     | 0/200 [00:00<?, ?it/s]

```

**Comment by arnavgarg1** [comment]
Hi @giurlanda, thanks for reporting this bug. I can confirm that I am able to repro this issue and I will come back to you shortly with an update on the fix.

**Comment by justinxzhao** [comment]
Hi @giurlanda,

Thanks for raising the issue. @arnavgarg1 actually ended up putting together a fix for this in https://github.com/ludwig-ai/ludwig/pull/3222.

I'll put together a 0.7.4 release with the fix.

**Comment by justinxzhao** [comment]
Hi @giurlanda, we just released v0.7.4 with the fix. If you `pip install ludwig --upgrade`, the error should go away. Please let us know if you run into any more issues!
