### ISSUE TITLE
The torchtext version 0.14.1  in the Docker image is incompatible with pytorch 2.0.0

### ISSUE THREAD

**Issue by abaletinskikh** [ludwig-ai/ludwig#3398]
the command to reproduce:
`podman run --entrypoint python ludwig-gpu:release-0.7  -c "import torchtext; print(torchtext.__version__);"`

Output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

**Comment by abaletinskikh** [comment]
fast workaround:
exec `pip install --force-reinstall  --no-deps torchtext==0.15.1` in the container

**Comment by justinxzhao** [comment]
Thanks @abaletinskikh for posting the issue and for posting a workaround.

Can confirm that version compatibility is particularly important for torch libraries, and indeed the latest compatible version of torchtext that we support is v0.15.1.

I notice that you are pulling down the `python ludwig-gpu:release-0.7` docker image. Was there something about the latest docker image `ludwigai/ludwig-gpu:master` that didn't work for you?

**Comment by tgaddair** [comment]
Hey @abaletinskikh, to clarify something, `ludwig-gpu:release-0.7` is a bit of an older image, I would recommend updating to `ludwig-gpu:release-0.7.4`, which should be the latest official image. Can you try using this image and letting us know if you see the same issue?
