### ISSUE TITLE
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'data.training.parquet/part.00000000.parquet', which is outside base dir 'data.training.parquet'

### ISSUE THREAD

**Issue by xxivk** [ludwig-ai/ludwig#3440]
Hello , 
am trying to run Ray as backend 

my yaml file : 
`input_features:
- type: number
  name: feature_1
  encoder:
    type: dense
    output_size: 64
- type: number
  name: feature_2
  encoder:
    type: dense
    output_size: 64
- type: number
  name: feature_3
  encoder:
    type: dense
    output_size: 64
combiner:
  type: transformer
  bias_initializer: zeros
  dropout: 0.2
  fc_activation: relu
  fc_dropout: 0
  fc_residual: false
  hidden_size: 64
  num_fc_layers: 0
  num_heads: 8
  num_layers: 5
  output_size: 64
  reduce_output: attention
  transformer_output_size: 256
  use_bias: true
  weights_initializer: xavier_uniform
defaults:
  number:
    preprocessing:
      normalization: zscore
trainer:
  epochs: 500
  early_stop: 200
  validation_field: assigned_label
  evaluate_training_set: true
  learning_rate: 0.0001
  batch_size: 128
  learning_rate_scheduler:
    warmup_evaluations: 5
  optimizer:
    type: adam
output_features:
- name: assigned_label
  type: number
  reduce_dependencies: sum
  reduce_input: sum
  preprocessing:
    computed_fill_value: 0
    fill_value: 0
    missing_value_strategy: drop_row
  loss:
    type: mean_squared_error
    weight: 1
  decoder:
    bias_initializer: zeros
    fc_activation: relu
    fc_bias_initializer: zeros
    fc_dropout: 0
    fc_output_size: 256
    fc_use_bias: true
    fc_weights_initializer: xavier_uniform
    num_fc_layers: 2
    type: regressor
    use_bias: true
    weights_initializer: xavier_uniform
backend:
  type: ray
  processor:
    type: dask
  trainer:
    strategy: horovod
`
[my csv data 
](https://github.com/dragosmc/ludwig-ray/blob/main/data.csv)

i run command :
**ludwig train --config config.yaml --dataset data.csv**

![image](https://github.com/ludwig-ai/ludwig/assets/42117836/9eb82836-b517-467f-bdaf-b6c7e2ee0e60)

i get error : 

`Users\crypto\Desktop\ludwig-ray-main>ludwig train --config config.yaml --dataset data.csv
C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Ray processor params: {'type': 'dask'}
Initializing new Ray cluster...
2023-06-24 02:16:38,286 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
███████████████████████
█ █ █ █  ▜█ █ █ █ █   █
█ █ █ █ █ █ █ █ █ █ ███
█ █   █ █ █ █ █ █ █ ▌ █
█ █████ █ █ █ █ █ █ █ █
█     █  ▟█     █ █   █
███████████████████████
ludwig v0.7.4 - Train  

╒════════════════════════╕
│ EXPERIMENT DESCRIPTION │
╘════════════════════════╛

╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════╕
│ Experiment name  │ experiment                                                                          │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ Model name       │ run                                                                                 │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ Output directory │ C:\Users\crypto\Desktop\ludwig-ray-main\results\experiment_run                      │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ ludwig_version   │ '0.7.4'                                                                             │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ command          │ ('C:\\Users\\crypto\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\ludwig ' │
│                  │  'train --config config.yaml --dataset data.csv')                                   │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ random_seed      │ 42                                                                                  │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ dataset          │ 'data.csv'                                                                          │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ data_format      │ 'csv'                                                                               │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ torch_version    │ '2.0.1+cu117'                                                                       │
├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ compute          │ {'gpu_type': 'NVIDIA GeForce GTX 1070 Ti', 'gpus_per_node': 2, 'num_nodes': 1}      │
╘══════════════════╧═════════════════════════════════════════════════════════════════════════════════════╛

╒═══════════════╕
│ LUDWIG CONFIG │
╘═══════════════╛

User-specified config (with upgrades):

{   'backend': {   'processor': {'type': 'dask'},
                   'trainer': {'strategy': 'horovod'},
                   'type': 'ray'},
    'combiner': {   'bias_initializer': 'zeros',
                    'dropout': 0.2,
                    'fc_activation': 'relu',
                    'fc_dropout': 0,
                    'fc_residual': False,
                    'hidden_size': 64,
                    'num_fc_layers': 0,
                    'num_heads': 8,
                    'num_layers': 5,
                    'output_size': 64,
                    'reduce_output': 'attention',
                    'transformer_output_size': 256,
                    'type': 'transformer',
                    'use_bias': True,
                    'weights_initializer': 'xavier_uniform'},
    'defaults': {'number': {'preprocessing': {'normalization': 'zscore'}}},
    'input_features': [   {   'encoder': {'output_size': 64, 'type': 'dense'},
                              'name': 'feature_1',
                              'type': 'number'},
                          {   'encoder': {'output_size': 64, 'type': 'dense'},
                              'name': 'feature_2',
                              'type': 'number'},
                          {   'encoder': {'output_size': 64, 'type': 'dense'},
                              'name': 'feature_3',
                              'type': 'number'}],
    'ludwig_version': '0.7.4',
    'output_features': [   {   'decoder': {   'bias_initializer': 'zeros',
                                              'fc_activation': 'relu',
                                              'fc_bias_initializer': 'zeros',
                                              'fc_dropout': 0,
                                              'fc_output_size': 256,
                                              'fc_use_bias': True,
                                              'fc_weights_initializer': 'xavier_uniform',
                                              'num_fc_layers': 2,
                                              'type': 'regressor',
                                              'use_bias': True,
                                              'weights_initializer': 'xavier_uniform'},
                               'loss': {   'class_weights': None,
                                           'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'assigned_label',
                               'preprocessing': {   'computed_fill_value': 0,
                                                    'fill_value': 0,
                                                    'missing_value_strategy': 'drop_row'},
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'number'}],
    'trainer': {   'batch_size': 128,
                   'early_stop': 200,
                   'epochs': 500,
                   'evaluate_training_set': True,
                   'learning_rate': 0.0001,
                   'learning_rate_scheduler': {'warmup_evaluations': 5},
                   'optimizer': {'type': 'adam'},
                   'validation_field': 'assigned_label'}}

Full config saved to:
C:\Users\crypto\Desktop\ludwig-ray-main\results\experiment_run/experiment/model/model_hyperparameters.json

╒═══════════════╕
│ PREPROCESSING │
╘═══════════════╛

Backend config has num_cpu not set. provision_preprocessing_workers() is a no-op in this case.
Using full raw dataset, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
(dask:('head-1-100-concat-cf4f63556c2490209555cd276f4ddfe4', 0) pid=12020) C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\dataframe\core.py:8093: UserWarning: Insufficient elements for `head`. 100 elements requested, only 15 elements available. Try passing larger `npartitions` to `head`.
(dask:('head-1-100-concat-cf4f63556c2490209555cd276f4ddfe4', 0) pid=12020)   warnings.warn(
[########################################] | 100% Completed | 106.11 ms
Building dataset: DONE
Writing preprocessed training set cache
[########################################] | 100% Completed | 103.62 ms
Writing preprocessed test set cache
[########################################] | 100% Completed | 102.22 ms
Writing preprocessed validation set cache
[########################################] | 100% Completed | 101.39 ms
Writing train set metadata
ray::_get_read_tasks() (pid=9060, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 1990, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 170, in create_reader  
    return _ParquetDatasourceReader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 204, in __init__       
    pq_ds = pq.ParquetDataset(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 1776, in __new__
    return _ParquetDatasetV2(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 2490, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 763, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 454, in _filesystem_dataset
    factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
  File "pyarrow\_dataset.pyx", line 2926, in pyarrow._dataset.FileSystemDatasetFactory.__init__
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'C:/Users/crypto/Desktop/ludwig-ray-main/data.training.parquet/part.00000000.parquet', which is outside base dir 'data.training.parquet', retrying in 1 seconds...
ray::_get_read_tasks() (pid=9060, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 1990, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 170, in create_reader  
    return _ParquetDatasourceReader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 204, in __init__       
    pq_ds = pq.ParquetDataset(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 1776, in __new__
    return _ParquetDatasetV2(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 2490, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 763, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 454, in _filesystem_dataset
    factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
  File "pyarrow\_dataset.pyx", line 2926, in pyarrow._dataset.FileSystemDatasetFactory.__init__
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'C:/Users/crypto/Desktop/ludwig-ray-main/data.training.parquet/part.00000000.parquet', which is outside base dir 'data.training.parquet', retrying in 2.381842725099008 seconds...
ray::_get_read_tasks() (pid=9060, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 1990, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 170, in create_reader  
    return _ParquetDatasourceReader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 204, in __init__       
    pq_ds = pq.ParquetDataset(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 1776, in __new__
    return _ParquetDatasetV2(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 2490, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 763, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 454, in _filesystem_dataset
    factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
  File "pyarrow\_dataset.pyx", line 2926, in pyarrow._dataset.FileSystemDatasetFactory.__init__
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'C:/Users/crypto/Desktop/ludwig-ray-main/data.training.parquet/part.00000000.parquet', which is outside base dir 'data.training.parquet', retrying in 4.947184847088574 seconds...
Traceback (most recent call last):
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ludwig\data\dataset\ray.py", line 58, in read_remote_parquet
    return read_parquet(path, filesystem=PyFileSystem(FSSpecHandler(fs)))
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 627, in read_parquet
    return read_datasource(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 380, in read_datasource
    requested_parallelism, min_safe_parallelism, read_tasks = ray.get(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\worker.py", line 2540, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::_get_read_tasks() (pid=9060, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\read_api.py", line 1990, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 170, in create_reader  
    return _ParquetDatasourceReader(**kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\data\datasource\parquet_datasource.py", line 204, in __init__       
    pq_ds = pq.ParquetDataset(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 1776, in __new__
    return _ParquetDatasetV2(
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\parquet\core.py", line 2490, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 763, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "C:\Users\crypto\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 454, in _filesystem_dataset
    factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
  File "pyarrow\_dataset.pyx", line 2926, in pyarrow._dataset.FileSystemDatasetFactory.__init__
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'C:/Users/crypto/Desktop/ludwig-ray-main/data.training.parquet/part.00000000.parquet', which is outside base dir 'data.training.parquet'`

- OS: Windows 
- Version: 10
- Python version 3.10.10 64bit
- Ludwig version  v0.7.4 

**Additional context**

**Comment by xxivk** [comment]
??

**Comment by ksbrar** [comment]
Hi @xxivk , thanks for bringing up this issue! CC @jeffkinnison 

We have encountered some flakiness with parquet directories recently, but when it happened it had involved the user-provided dataset itself rather than the working directory. We don't have an immediate mitigation at this time, but we are looking into it and will get back to you soon.

**Comment by xxivk** [comment]
good , i tried to fix it installing all versions of luwdig / Ray  still failed  . so  am waiting for the solution

**Comment by xxivk** [comment]
Hey guys after the update of ludwig still same issue

**Comment by jeffkinnison** [comment]
Hi @xxivk, just wanted to post an update here. So far, I have not been able to repro the issue. Training with your config and data succeeds on OSX with Python 3.8, 3.9, and 3.10. I'm in the process of setting up a Windows environment to try to repro, and will update again with results when that is up and running.

**Comment by jeffkinnison** [comment]
Hi @xxivk, just wanted to let you know that the parquet fix was merged! Does that resolve the issue?

**Comment by xxivk** [comment]
> 

Thanks for informing me mate ! you done Great job.
