### ISSUE TITLE
Can't use Docker image ludwigai/ludwig-gpu. OSError: /opt/conda/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

### ISSUE THREAD

**Issue by CostaFernando** [ludwig-ai/ludwig#3441]
**Describe the bug**
Hi, guys!

I'm trying to use the Docker image ludwigai/ludwig-gpu in AWS EC2 (I tried with Amazon Linux 2023 AMI and Ubuntu Server 20.04 LTS AMI), but I get this error: `OSError: /opt/conda/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll`, when I try to execute any command, for example `docker run -t -i ludwigai/ludwig-gpu check_install`.

This is the full error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 178, in main
    CLI()
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 68, in __init__
    getattr(self, args.command)()
  File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 166, in check_install
    from ludwig import check
  File "/opt/conda/lib/python3.10/site-packages/ludwig/check.py", line 5, in <module>
    from ludwig.api import LudwigModel
  File "/opt/conda/lib/python3.10/site-packages/ludwig/api.py", line 40, in <module>
    from ludwig.backend import Backend, initialize_backend, provision_preprocessing_workers
  File "/opt/conda/lib/python3.10/site-packages/ludwig/backend/__init__.py", line 22, in <module>
    from ludwig.backend.base import Backend, LocalBackend
  File "/opt/conda/lib/python3.10/site-packages/ludwig/backend/base.py", line 29, in <module>
    from ludwig.data.cache.manager import CacheManager
  File "/opt/conda/lib/python3.10/site-packages/ludwig/data/cache/manager.py", line 8, in <module>
    from ludwig.data.dataset.base import DatasetManager
  File "/opt/conda/lib/python3.10/site-packages/ludwig/data/dataset/base.py", line 21, in <module>
    from ludwig.utils.defaults import default_random_seed
  File "/opt/conda/lib/python3.10/site-packages/ludwig/utils/defaults.py", line 24, in <module>
    from ludwig.features.feature_registries import get_input_type_registry
  File "/opt/conda/lib/python3.10/site-packages/ludwig/features/feature_registries.py", line 33, in <module>
    from ludwig.features.audio_feature import AudioFeatureMixin, AudioInputFeature
  File "/opt/conda/lib/python3.10/site-packages/ludwig/features/audio_feature.py", line 25, in <module>
    from ludwig.features.base_feature import BaseFeatureMixin
  File "/opt/conda/lib/python3.10/site-packages/ludwig/features/base_feature.py", line 23, in <module>
    from ludwig.decoders.registry import get_decoder_cls
  File "/opt/conda/lib/python3.10/site-packages/ludwig/decoders/__init__.py", line 2, in <module>
    import ludwig.decoders.generic_decoders  # noqa
  File "/opt/conda/lib/python3.10/site-packages/ludwig/decoders/generic_decoders.py", line 23, in <module>
    from ludwig.decoders.base import Decoder
  File "/opt/conda/lib/python3.10/site-packages/ludwig/decoders/base.py", line 20, in <module>
    from ludwig.utils.torch_utils import LudwigModule
  File "/opt/conda/lib/python3.10/site-packages/ludwig/utils/torch_utils.py", line 13, in <module>
    from ludwig.utils.strings_utils import SpecialSymbol
  File "/opt/conda/lib/python3.10/site-packages/ludwig/utils/strings_utils.py", line 30, in <module>
    from ludwig.utils.tokenizers import get_tokenizer_from_registry
  File "/opt/conda/lib/python3.10/site-packages/ludwig/utils/tokenizers.py", line 923, in <module>
    import torchtext
  File "/opt/conda/lib/python3.10/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/opt/conda/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll
```

**To Reproduce**
I only tried in AWS EC2 instances, so I don't know if it's happening in other contexts.

1. Using an AWS EC2 instance with Amazon Linux 2023 AMI or Ubuntu Server 20.04 LTS AMI, with g4dn.2xlarge instance type.
2. Make sure that Docker is installed.
3. Run `docker run -t -i ludwigai/ludwig-gpu check_install`.

**Expected behavior**
I tested with ludwigai/ludwig and it worked properly, so it appear to be a problem with the gpu image version.

Is anyone having this problem? Is there a workaround?

**Comment by CostaFernando** [comment]
@abidwael @tgaddair , I saw that you committed to the ludwig-gpu recently. Do you have any insights about this problem?

**Comment by jppgks** [comment]
@CostaFernando I upgraded the ludwig-gpu image to PyTorch 2.0.0. This seems to have resolved the "undefined symbol" issue due to version mismatches between torch and torchtext. The new image has been pushed to Docker Hub.

**Comment by CostaFernando** [comment]
Thank you for your help, @jppgks! I tested and it works now.
