### ISSUE TITLE
ZeroDivisionError in batch_size_tuner.py

### ISSUE THREAD

**Issue by xlgp2171** [ludwig-ai/ludwig#3475]
**Describe the bug**  
This exception was raised while I was training the data in the tutorial (Image Classification), and after debugging it was found that the `med_duration_s` parameter was 0.0.  
  

**To Reproduce**  
1. Refer to the tutorial https://ludwig.ai/latest/examples/mnist/
2. Download the MNIST dataset
3. Follow the tutorial to write `config.yaml`
4. Run command: `ludwig train --dataset mnist.parquet --config config.yaml`  
  

**Expected behavior**  
The command was executed and the data training was successful.  
  

**Screenshots**  
Here is log and error messages:  
```text
╒═══════════════╕
│ PREPROCESSING │
╘═══════════════╛

Using full raw dataset, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Inferring num_channels from the first 100 images.
  images with 1 channels: 100
Using 1 channels because it is the majority in sample. If an image with a different depth is read, will attempt to convert to 1 channels.
To explicitly set the number of channels, define num_channels in the preprocessing dictionary of the image input feature config.
Building dataset: DONE
Writing preprocessed training set cache
Writing preprocessed test set cache
Writing preprocessed validation set cache
Writing train set metadata

Dataset Statistics
╒════════════╤═══════════════╤════════════════════╕
│ Dataset    │   Size (Rows) │ Size (In Memory)   │
╞════════════╪═══════════════╪════════════════════╡
│ Training   │         49000 │ 7.15 Mb            │
├────────────┼───────────────┼────────────────────┤
│ Validation │          7000 │ 1.02 Mb            │
├────────────┼───────────────┼────────────────────┤
│ Test       │         14000 │ 2.04 Mb            │
╘════════════╧═══════════════╧════════════════════╛

╒═══════╕
│ MODEL │
╘═══════╛

Warnings and other logs:
Tuning batch size...
Tuning batch size...
Exploring batch_size=2
Throughput at batch_size=2: 154.67434 samples/s
Exploring batch_size=4
Throughput at batch_size=4: 489.84572 samples/s
Exploring batch_size=8
Throughput at batch_size=8: 533.27027 samples/s
Exploring batch_size=16
Throughput at batch_size=16: 2460.63374 samples/s
Exploring batch_size=32
Traceback (most recent call last):
  File "D:\DevelopTool\Python\Python_3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python_3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\CT-C102\CT-C102-41\venv\Scripts\ludwig.exe\__main__.py", line 7, in <module>
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\cli.py", line 178, in main
    CLI()
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\cli.py", line 68, in __init__
    getattr(self, args.command)()
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\cli.py", line 73, in train
    train.cli(sys.argv[2:])
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\train.py", line 395, in cli
    train_cli(**vars(args))
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\train.py", line 185, in train_cli
    model.train(
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\api.py", line 613, in train
    self._tune_batch_size(trainer, training_set, random_seed=random_seed)
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\api.py", line 802, in _tune_batch_size
    tuned_batch_size = trainer.tune_batch_size(self.config_obj.to_dict(), dataset, random_seed=random_seed)
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\trainers\trainer.py", line 385, in tune_batch_size
    return evaluator.select_best_batch_size(len(training_set), max_batch_size, max_trials)
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\utils\batch_size_tuner.py", line 54, in select_best_batch_size
    samples_per_sec = self.evaluate(batch_size, total_steps=5)
  File "E:\CT-C102\CT-C102-41\venv\lib\site-packages\ludwig\utils\batch_size_tuner.py", line 99, in evaluate
    return batch_size / med_duration_s
ZeroDivisionError: float division by zero
```  
  

**Environment (please complete the following information):**  
  
- OS: windows
- Version: 11
- Python version: 3.10.11
- Ludwig version: 0.7.4
  

**Additional context**  
After local debugging, the `durations` parameter value is:  
```text
[0.013508796691894531, 0.0, 0.0, 0.015627384185791016, 0.0]  
```  
So,the return parameter `med_duration_s` is 0.0  
As a temporary solution:  
```python
return batch_size / max(med_duration_s, 0.01)
```

**Comment by tgaddair** [comment]
Hey @xlgp2171, thanks for reporting this issue. Definitely makes sense that this could happen in some cases. I think your workaround is fine. I can put together a quick PR to fix this. Thanks!
