### ISSUE TITLE
Docker image crashes when checking utilization

### ISSUE THREAD

**Issue by khellan** [ludwig-ai/ludwig#3726]
**Describe the bug**
Training Llama in Docker image crashes because the recently added utilization logging is not available.

**To Reproduce**
 Run docker image **ludwigai/ludwig-gpu:master** with this
```
        ludwig train \
        --config /data/training.yaml \
        --data_format csv \
        --experiment_name llama-20231013-1 \
        --model_name english_classes \
        --test_set english_significant_test.csv \
        --training_set english_significant_train.csv \
        --validation_set english_significant_val.csv
````
My training.yaml:
input_features:
```
 - name: english
   type: text
   encoder:
     type: auto_transformer
     pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
     trainable: true
     adapter: 
      type: lora


output_features:
 - name: label
   type: category
  

trainer:
  learning_rate: 1.0e-05
  epochs: 3
````

Unfortunately, I can't provide training data.

**Expected behavior**
Training runs as it has before.

**Log**
````
2023-10-13T09:40:15Z [job] ╒══════════╕
2023-10-13T09:40:15Z [job] │ TRAINING │
2023-10-13T09:40:15Z [job] ╘══════════╛
2023-10-13T09:40:15Z [job] Creating fresh model training run.
2023-10-13T09:40:15Z [job] Training for 12579 step(s), approximately 3 epoch(s).
2023-10-13T09:40:15Z [job] Early stopping policy: 5 round(s) of evaluation, or 20965 step(s), approximately 5 epoch(s).
2023-10-13T09:40:15Z [job] Starting with step 0, epoch: 0
2023-10-13T09:40:16Z [job] Traceback (most recent call last):
2023-10-13T09:40:16Z [job] File "/opt/conda/bin/ludwig", line 8, in <module>
2023-10-13T09:40:16Z [job] sys.exit(main())
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 191, in main
2023-10-13T09:40:16Z [job] CLI()
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 71, in __init__
2023-10-13T09:40:16Z [job] getattr(self, args.command)()
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/cli.py", line 76, in train
2023-10-13T09:40:16Z [job] train.cli(sys.argv[2:])
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/train.py", line 395, in cli
2023-10-13T09:40:16Z [job] train_cli(**vars(args))
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/train.py", line 185, in train_cli
2023-10-13T09:40:16Z [job] model.train(
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/api.py", line 654, in train
2023-10-13T09:40:16Z [job] train_stats = trainer.train(
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/trainers/trainer.py", line 967, in train
2023-10-13T09:40:16Z [job] should_break = self._train_loop(
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/trainers/trainer.py", line 1143, in _train_loop
2023-10-13T09:40:16Z [job] self.write_step_summary(
2023-10-13T09:40:16Z [job] File "/opt/conda/lib/python3.10/site-packages/ludwig/trainers/trainer.py", line 495, in write_step_summary
2023-10-13T09:40:16Z [job] torch.cuda.device(i).utilization(),
2023-10-13T09:40:16Z [job] AttributeError: 'device' object has no attribute 'utilization'
Training:   0%|          | 0/12579 [00:01<?, ?it/s] | 0/12579 [00:00<?, ?it/s]
2023-10-13T09:40:19Z [ovh] Job status is now FINALIZING : JOB_FAILED : Job failed with exit code 1
```
**Environment (please complete the following information):**

- OS: Linux (Docker Image)
- Docker Image version: ludwigai/ludwig-gpu:master
- Python version: 3.10.11 (default in the docker container)
- Ludwig version: 0.8 (from the docker container)

GPU
1 x Tesla-V100S (40GB RAM)

**Additional context**
I run the image as an OVH training job. I have trained with the same config several times over the latest week with no problems.
There is nothing special about the way things are run in OVH. The training job justs run the docker image on the server.

**Comment by arnavgarg1** [comment]
Hi @khellan, thanks for flagging this issue.

Based on the error stack trace, it seems like the error originates from some changes made in this pull request that was recently merged in 2 days ago: https://github.com/ludwig-ai/ludwig/commit/6d74d21d71ecc7c125598a93f600b95aa35e2811. 

This error does feel strange given that utilization is a supported method for `torch.cuda.device()` objects: 
https://pytorch.org/docs/stable/_modules/torch/cuda.html#device, but I also found a different function call for this here: https://pytorch.org/docs/stable/generated/torch.cuda.utilization.html#torch.cuda.utilization

Perhaps, the issue here is that we are doing `torch.cuda.device(i).utilization()` instead of `torch.cuda.utilization(device=f"cuda:{i}"})`. 

cc: @justinxzhao - can you please take a look when you get a chance?

**Comment by arnavgarg1** [comment]
@khellan I am able to reproduce your error - let me work on a fix

**Comment by arnavgarg1** [comment]
Hi @khellan - I just merged a fix into Ludwig master - give it about 30 minutes for a new docker image to built. After that, are you able to retry with the latest docker image and confirm that you don't run into this error again?

**Comment by arnavgarg1** [comment]
@khellan Images are built if you want to give it a try!

**Comment by arnavgarg1** [comment]
> I can confirm that it works on my system again. Thanks for fixing this, @arnavgarg1 !

Thanks for confirming!
