### ISSUE TITLE
Ludwig serve <no maximum length is provided>

### ISSUE THREAD

**Issue by Tigranchick** [ludwig-ai/ludwig#3751]
**Describe the bug**
i am  run ludwig serve with 
'ludwig serve --model_path=/home/ubuntu/ludwig/api_experiment_run/model'
Everything load as expected but when i am trying curl to the api with
'curl http://0.0.0.0:8000/predict -X POST -F 'instruction=test instruction'
i got 
{"error":"Unexpected Error: could not run inference on model"}

logs from the serve
ludwig serve --model_path=/home/ubuntu/ludwig/api_experiment_run/model

ludwig v0.8.6 - Serve

We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [01:41<00:00, 51.00s/it]
INFO:     Started server process [14417]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
/home/ubuntu/.local/lib/python3.10/site-packages/ludwig/features/feature_utils.py:102: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(sequence_probabilities))
Failed to run predict: Out of range float values are not JSON compliant
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ludwig/serve.py", line 92, in predict
    return NumpyJSONResponse(resp)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ludwig/utils/server_utils.py", line 168, in render
    return json.dumps(
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
INFO:     127.0.0.1:40206 - "POST /predict HTTP/1.1" 500 Internal Server Error

**To Reproduce**

1. I used this collab for fine tuning https://colab.research.google.com/drive/1r4oSEwRJpYKBPM0M0RSh0pBEYK_gBKbe
2. Upload model from fine tuning to aws ec2  g4dn.xlarge with T4 
3. Install python 3.10 and pip install ludwig[full]
4. Run serve ludwig serve --model_path=/home/ubuntu/ludwig/api_experiment_run/model
5. In another terminal tried 'curl http://0.0.0.0:8000/predict -X POST -F 'instruction=test instruction'

**Expected behavior**
Code 200 and output of the instruction

**Screenshots**

**Environment (please complete the following information):**

- OS: Ubuntu 22 on g4dn.xlarge aws 
- Python version 3.10
- Ludwig version  v0.8.6 

**Additional context**
I understand that the reason is most likely the lack of something in the environment, can you tell me how to configure it correctly

**Comment by Oddadmix** [comment]
Facing the same issue, I am trying to fine-tune facebook/opt-350m

**Comment by Oddadmix** [comment]
@justinxzhao, any thoughts please?

**Comment by Oddadmix** [comment]
@alexsherstinsky, can you please help?

**Comment by alexsherstinsky** [comment]
@Oddadmix Thank you for bringing this up -- I see that this issue is coming from over a month ago (sorry for the delay).

So we are fine-tuning the model in Colab and then copying it to EC2 with the GPU in it.  Could you please provide the following:
1. Exact command used to upload the model to an ubuntu machine EC2; and
2. Listing of the full path to and the contents of the model directory on the ubuntu EC2 machine.

We will try to troubleshoot from there.

In the mean time, would it be possible for you to repeat your experiment (including the training) on the latest version of Ludwig (it is now version 0.9)?

Thank you very much!

**Comment by Oddadmix** [comment]
@alexsherstinsky thank you so much. Let me give that a try and let you know. I appreciate your time and reply

**Comment by fwka92** [comment]
ive encountered exactly the same issue and found out the reason: when the response is generated the json dict also contains an assistant probability. if that probability for some reason is not a default numerical value, in my case it was -inf, then the json.dumps function ofc fails because it cant encode it.

i did hardcode a quick and dirty fix into my source code: in server utils.py i did add a line that replaces the content of the dict when assistant probabiltiy is not numerical it replaces it with 0.

the generated response is surprisingly very well, even when this value is non-numerical after finetuning.

**Comment by gireesh99** [comment]
Any update on this issue.. This problem is still happening

**Comment by mhabedank** [comment]
@gireesh99 thanks for getting back in touch. It's been a while that this was discussed. is it still a problem for you? I think there where several places where the JSON was not compliant to the JSON standard. We need to address that but I guess the prio is not that high currently. Maybe you can hell us fixing the issue?

**Comment by dhoepp** [comment]
Submitted fix in #4058
