### ISSUE TITLE
ValueError: Please specify 'target_modules' in 'peft_config'

### ISSUE THREAD

**Issue by mhillebrand** [ludwig-ai/ludwig#3758]
**Describe the bug**
When I try to finetune Mistral, I get this error: `ValueError: Please specify 'target_modules' in 'peft_config'`

**To Reproduce**
```python
import csv
import pandas as pd

from ludwig.api import LudwigModel
from utilz import cwd

train_data_path = '/opt/topics/data/pairs.tsv'
df = pd.read_csv(train_data_path, sep='\t', header=None, quoting=csv.QUOTE_ALL)
df = df.dropna()
df.columns = ['input', 'output']

model = LudwigModel(config=cwd('ludwig.yaml'))
results = model.train(dataset=df)
```

```yaml
model_type: llm
base_model: ehartford/dolphin-2.1-mistral-7b

prompt:
  template: |
    ### Instruction:
    Extract topics found in the input text.

    ### Input:
    {input}

    ### Response:

input_features:
  - name: input
    type: text
    preprocessing:
      max_sequence_length: 2048
      lowercase: false

output_features:
  - name: output
    type: text
    preprocessing:
      max_sequence_length: 2048
      lowercase: false

adapter:
  type: lora

quantization:
  bits: 4

trainer:
  type: finetune
  learning_rate: 0.0001
  batch_size: 1
  gradient_accumulation_steps: 16
  epochs: 4
  learning_rate_scheduler:
    warmup_fraction: 0.01
```

```bash
Traceback (most recent call last):
  File "/opt/topics/debug.py", line 34, in <module>
    results = model.train(dataset=df[:1_000])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/api.py", line 619, in train
    with self.backend.create_trainer(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/backend/base.py", line 293, in create_trainer
    return trainer_cls(config=config, model=model, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/trainers/trainer_llm.py", line 418, in __init__
    super().__init__(
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/trainers/trainer.py", line 179, in __init__
    self.model.prepare_for_training()
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/models/llm.py", line 259, in prepare_for_training
    self.initialize_adapter()
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/ludwig/models/llm.py", line 247, in initialize_adapter
    self.model = get_peft_model(self.model, peft_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/mapping.py", line 106, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/peft_model.py", line 889, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/peft_model.py", line 111, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/tuners/lora.py", line 274, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 88, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 205, in inject_adapter
    peft_config = self._prepare_adapter_config(peft_config, model_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/ludwig/lib/python3.11/site-packages/peft/tuners/lora.py", line 550, in _prepare_adapter_config
    raise ValueError("Please specify `target_modules` in `peft_config`")
ValueError: Please specify `target_modules` in `peft_config`
```

**Environment (please complete the following information):**

- OS: Linux Mint (latest)
- Python 3.11.4
- Ludwig 0.8.6

**Additional context**
I got some assistance from @alexsherstinsky, who told me to install the latest versions of ludwig, transformers, and peft from their repositories. Doing this did indeed solve the problem, but it broke the `spacy-transformers` dependency. I'm not sure how Ludwig uses spaCy or if it even needs `spacy-transformers`.

```bash
pip install -U git+https://github.com/ludwig-ai/ludwig.git@master
pip install -U git+https://github.com/huggingface/transformers
pip install -U git+https://github.com/huggingface/peft.git
```

**Comment by geoffreyangus** [comment]
Hi @mhillebrand, thanks for keeping this issue up-to-date! Will take a look at the spacy issue, but will close this one since it seems resolved.
