### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by robhheise** [ludwig-ai/ludwig#3960]
**Describe the bug**
When importing ludwig.backend and initializing the ray cluster I am getting the following error: 
/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):
  File "/Users/robertheise/Documents/SD/accelator/model.py", line 46, in <module>
    backend = initialize_backend(backend_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/__init__.py", line 109, in initialize_backend
    backend = create_backend(**backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/__init__.py", line 103, in create_backend
    return backend_registry[type](**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/__init__.py", line 79, in create_ray_backend
    from ludwig.backend.ray import RayBackend
  File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/ray.py", line 23, in <module>
    import dask
ModuleNotFoundError: No module named 'dask'

**To Reproduce**
backend_config = {
    "type": "ray",
    "processor": {
        "parallelism": 6,
        "type": "dask",
    },
    "trainer": {
        "use_gpu": False,
        "num_workers": 3,
        "resources_per_worker": {
            "CPU": 2,
            "GPU": 0,
        },
    },
}
backend = initialize_backend(backend_config)

**Expected behavior**
I would expect that all dependencies are installed as part of the pip install ludwig

**Environment (please complete the following information):**

- OS: \[e.g. iOS\] Macbook Pro Apple M1 
- Version \[e.g. 22\] Ventura 13.3.1 (a)
- Python version: 3.11
- Ludwig version ludwig v0.10.0

**Comment by arnavgarg1** [comment]
Hi @robhheise! 

Can you also try `pip install ludwig[distributed]` in addition `pip install ludwig` and see if that fixes the issue for you?

**Comment by robhheise** [comment]
% pip install ludwig[distributed]
zsh: no matches found: ludwig[distributed]

**Comment by robhheise** [comment]
Seeing other dependency issues across other modules:
ludwig visualize is throwing this error:
 File "/Users/robertheise/Documents/SD/pythonProject/venv/lib/python3.11/site-packages/ludwig/utils/visualization_utils.py", line 24, in <module>
    import ptitprince as pt
ModuleNotFoundError: No module named 'ptitprince' 

File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/__init__.py", line 79, in create_ray_backend
    from ludwig.backend.ray import RayBackend
  File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/ludwig/backend/ray.py", line 26, in <module>
    import ray
ModuleNotFoundError: No module named 'ray'

**Comment by arnavgarg1** [comment]
Ah I see! Since you're using zsh, try this instead:

```bash
pip install "ludwig[distributed]"
pip install "ludwig[viz]"
```

**Comment by robhheise** [comment]
Could not find a recent CMake to build Horovod. Attempting to install CMake 3.13 to a temporary location via pip.
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/pip-install-8ebknxnv/cmake_fba7574486614c1da02c4746cc4706c7/setup.py", line 7, in <module>
                from skbuild import setup
            ModuleNotFoundError: No module named 'skbuild'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      
      [notice] A new release of pip is available: 23.1.2 -> 24.0
      [notice] To update, run: pip install --upgrade pip
      Traceback (most recent call last):
        File "/private/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/pip-install-_17id8g8/horovod_b513aea64f624a6293522a0e7a5918d0/setup.py", line 86, in get_cmake_bin
          _ = subprocess.check_output(["pip", "install", "--target", cmake_temp_dir.name, "cmake~=3.13.0"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['pip', 'install', '--target', '/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/horovod-cmake-tmpca59j47c', 'cmake~=3.13.0']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/pip-install-_17id8g8/horovod_b513aea64f624a6293522a0e7a5918d0/setup.py", line 213, in <module>
          setup(name='horovod',
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/robertheise/Documents/SD/accelator/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/pip-install-_17id8g8/horovod_b513aea64f624a6293522a0e7a5918d0/setup.py", line 106, in build_extensions
          cmake_bin = get_cmake_bin()
                      ^^^^^^^^^^^^^^^
        File "/private/var/folders/gp/34_5265x33l8ly1yb_x21qph0000gn/T/pip-install-_17id8g8/horovod_b513aea64f624a6293522a0e7a5918d0/setup.py", line 88, in get_cmake_bin
          raise RuntimeError("Failed to install temporary CMake. "
      RuntimeError: Failed to install temporary CMake. Please update your CMake to 3.13+ or set HOROVOD_CMAKE appropriately.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
  Building wheel for pylatex (pyproject.toml) ... done
  Created wheel for pylatex: filename=PyLaTeX-1.4.2-py3-none-any.whl size=43562 sha256=df055787e6d1121440b30e5d118c1b7e8617f43658831c99616b91c5bd80180b
  Stored in directory: /Users/robertheise/Library/Caches/pip/wheels/2d/ec/ac/90369f9c675e91e3da4dd379289a34073b7d14aed6a923b060
Successfully built GPUtil ludwig whylogs-sketching bootstrapped pylatex
Failed to build tokenizers horovod
ERROR: Could not build wheels for tokenizers, horovod, which is required to install pyproject.toml-based projects

**Comment by arnavgarg1** [comment]
I see. Hmm. One last thing before I try and repro this myself - any chance you can use Py38, Py39 or P310? I don't think we support Py311 yet.

**Comment by robhheise** [comment]
Good catch, switched to py3.10 and both viz and distributed installs are working.

**Comment by arnavgarg1** [comment]
@robhheise great to hear! Going to close this issue :)
