### ISSUE TITLE
PyYAML error while installing with python 3.12

### ISSUE THREAD

**Issue by fmatray** [ludwig-ai/ludwig#3987]
**Describe the bug**
The PyYAML dependency error while installing with python 3.12.2.

**To Reproduce**

1. Install python 3.12
2. pip install ludwig

**Expected behavior**
A successfully installation :-)

**Screenshots**
'''
[...]
Collecting PyYAML!=5.4.*,<6.0.1,>=3.12 (from ludwig[full])
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/dz/23t0qk7d6k5g1jrh9vqv6yh80000gn/T/pip-build-env-o_ojprq7/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
'''

**Environment (please complete the following information):**

- OS:  macOS Sonoma 14.3.1 (Up to date)
- Version \[e.g. 22\]
- Python version : 3.12.2
- Ludwig version : 0.10.2

**Additional context**
For python 3.12.2 the right PyYAML version is 6.0.1.
The error seems to be in the requirement "PyYAML!=5.4.*,**<6.0.1**,>=3.12"

**Comment by diegotxegp** [comment]
I had a series of errors at the moment of installing dependencies on Python 3.12 so I decided to use with Python 3.11.9. Just installing everything again and it works. I hope my answer was what you were expecting. :)

**Comment by alexsherstinsky** [comment]
@diegotxegp Ludwig does not yet support Python versions beyond Python-3.10 (it is good that you got it working with Python 3.11.9).  If you are interested in undertaking the project of getting Ludwig to work on the latest version(s) of Python, you are welcome to become a contributor.  As an open source project, Ludwig benefits greatly from contributors, and the Ludwig contributors are celebrated in the Ludwig community.  Please let us know.  Thank you.
