### ISSUE TITLE
Errors opening DevContainer on Windows

### ISSUE THREAD

**Issue by CraigRichards** [ludwig-ai/ludwig#4017]
**Describe the bug**
I've cloned the repo and select open in DevContainer and it continually fails on windows.
I noticed the file has not been updated in a couple of years and not sure it is still working.

**To Reproduce**
Clone the repo and open in VSCode

# Error
ERROR: failed to solve: process "/bin/sh -c apt-get update && export DEBIAN_FRON
TEND=noninteractive     && apt-get purge -y imagemagick imagemagick-6-common
 && bash /tmp/common-debian.sh \"${INSTALL_ZSH}\" \"${USERNAME}\" \"${USER_UID}\
" \"${USER_GID}\" \"${UPGRADE_PACKAGES}\" \"true\" \"true\"     && apt-get autor
emove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*" did not complete su
ccessfully: exit code: 4
[84897 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ADMINI~1\AppData\Local\Temp\devcontainercli\container-features\0.66.0-1722219989432\Dockerfile-with-features -t vsc-ludwig-b1b1335e522af6cb2005112d51682449356a8381188667bce31ef50acb4d816e --target dev_containers_target_stage --build-context dev_containers_feature_content_source=C:\Users\ADMINI~1\AppData\Local\Temp\devcontainercli\container-features\0.66.0-1722219989432 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=1000 --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp d:\study\ludwig
[84897 ms]     at mtA (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:466:1933)
[84897 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[84897 ms]     at async Pm (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:465:1856)
[84897 ms]     at async NH (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:465:610)
[84897 ms]     at async KtA (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:482:3771)
[84897 ms]     at async eB (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:482:4886)
[84897 ms]     at async hrA (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:663:200)
[84897 ms]     at async lrA (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js:662:13452)
[84907 ms] Exit code 1
[84914 ms] Command failed: C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.375.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-5a8faf79-a211-450a-bc21-4066625cf40e1722219983622 --workspace-folder d:\study\ludwig --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\study\ludwig --id-label devcontainer.config_file=d:\study\ludwig\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\study\ludwig\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-a5854439-7e55-45cc-be07-c6588b48c0a5.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[84914 ms] Exit code 1

**Environment (please complete the following information):**

- OS: Windows
- Version 11
- Python version
- Ludwig version

**Comment by mhabedank** [comment]
Hi @CraigRichards thanks for writing this issue. We are currently undergoing a transition in the project organization. We will have a look into it as soon as we have time for it.
