### ISSUE TITLE
Ludwig not working on Kaggle

### ISSUE THREAD

**Issue by mhabedank** [ludwig-ai/ludwig#4036]
**Describe the bug**
Could not install Ludwig on Kaggle to use it

**To Reproduce**

1. Create Notebook
2. run `!pip install ludwig`

**Expected behavior**
Ludwig is installed an can be used.

**Screenshots**
```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 319, in <module>
        File "<string>", line 311, in setup_package
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-build-env-z2d3tatc/overlay/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 29, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Environment (please complete the following information):**

- Kaggle Notebook

**Comment by w4nderlust** [comment]
hey! this is fixed in Ludwig v0.11.0 which we just released. we completely overhauled all dependencies, removed torchtext, upgraded to Python 3.12 / PyTorch 2.6 / Ray 2.54, and published a clean wheel to PyPI. you can install it with `pip install ludwig==0.11.0`. let us know if you run into any other issues!
